server:
  port: 8080

spring:
  application:
    name: transactions-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/santander_db
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  security:
    jwt:
      secret: "y7P5KxD1kG2mA9uF0tB4rQ6vN8eJ3sH1pL2zC7wR5xM0oV8qY4fU9dT6nE3bI1"
      expiration: 3600000

